/**
 * Main Data Initialization
 */
async function initGitHubData() {
    const statsContainer = document.getElementById('github-stats-container');
    const prList = document.getElementById('pr-list');
    const prContainer = document.getElementById('pr-container');
    const projectCards = document.querySelectorAll('.card-link[data-repo]');

    try {
        // Fetch your local JSON generated by GitHub Actions
        const response = await fetch('data.json');
        if (!response.ok) throw new Error('Data file not found');
        const data = await response.json();

        // 1. Render Stats
        if (statsContainer && data.stats) {
            statsContainer.innerHTML = `
                <div class="stats-grid">
                    <div class="stat-item">
                        <span class="stat-value">${data.stats.commits}</span>
                        <span class="stat-label">Commits</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-value">${data.stats.repos}</span>
                        <span class="stat-label">Repos</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-value">${data.stats.followers}</span>
                        <span class="stat-label">Followers</span>
                    </div>
                    <div class="stat-item">
                        <span class="stat-value">${data.stats.since}</span>
                        <span class="stat-label">Since</span>
                    </div>
                </div>
            `;
        }

        // 2. Render PRs
        if (prList && data.prs) {
            const loadingText = prContainer.querySelector('.loading-text');
            if (loadingText) loadingText.remove();
            
            prList.innerHTML = data.prs.map(pr => `
                <li class="pr-item">
                    <a href="${pr.url}" target="_blank" rel="noopener">${pr.title}</a>
                    <span class="pr-repo">${pr.repo}</span>
                </li>
            `).join('');
        }

        // 3. Render Stars
        projectCards.forEach(card => {
            const repoName = card.getAttribute('data-repo').toLowerCase();
            const badge = card.querySelector('.star-badge');
            if (badge && data.stars[repoName] !== undefined) {
                badge.innerHTML = `󰓈 ${data.stars[repoName]}`;
            }
        });

    } catch (err) {
        console.error('Error loading data.json:', err);
        if (statsContainer) statsContainer.innerHTML = '<p class="loading-text">Stats currently unavailable</p>';
    }
}

/**
 * UI Setup Functions (Sidebar, Discord Copy, etc.)
 * These remain largely the same as your original script
 */
function setupDiscordCopy() {
    const handle = document.querySelector('.discord-handle');
    if (!handle) return;
    handle.addEventListener('click', async () => {
        try {
            const textToCopy = handle.getAttribute('data-handle') || handle.innerText.replace('@', '');
            await navigator.clipboard.writeText(textToCopy);
            const valSpan = handle.querySelector('.contact-value');
            const originalText = valSpan.innerText;
            valSpan.innerText = 'Copied!';
            handle.classList.add('copied');
            setTimeout(() => {
                valSpan.innerText = originalText;
                handle.classList.remove('copied');
            }, 2000);
        } catch (err) { console.error(err); }
    });
}

function setupSidebar() {
    const sidebar = document.getElementById('sideNav');
    const overlay = document.getElementById('overlay');
    const openBtn = document.getElementById('sidebarOpen');
    const closeBtn = document.getElementById('sidebarClose');
    
    const toggle = (s) => {
        sidebar.classList.toggle('active', s);
        overlay.classList.toggle('active', s);
        document.body.style.overflow = s ? 'hidden' : '';
    };

    openBtn?.addEventListener('click', () => toggle(true));
    closeBtn?.addEventListener('click', () => toggle(false));
    overlay?.addEventListener('click', () => toggle(false));
    document.querySelectorAll('.nav-item').forEach(l => l.addEventListener('click', () => toggle(false)));
}

// Initialize on load
document.addEventListener('DOMContentLoaded', () => {
    initGitHubData();
    setupDiscordCopy();
    setupSidebar();
});